syntax = "proto3";

package richcrab.v1;

import "common.proto";
import "google/protobuf/timestamp.proto";

service JoinService {
  rpc IssueJoinTicketByPin(IssueJoinTicketByPinRequest) returns (IssueJoinTicketResponse);
  rpc IssueJoinTicketByInvite(IssueJoinTicketByInviteRequest) returns (IssueJoinTicketResponse);
}

message JoinTicket {
  string token = 1;
  RoomId room_id = 2;
  string display_name = 3;
  google.protobuf.Timestamp issued_at = 4;
  google.protobuf.Timestamp expires_at = 5;
}

message IssueJoinTicketByPinRequest {
  string pin = 1;
  string display_name = 2;
}

message IssueJoinTicketByInviteRequest {
  string invite_token = 1;
  string display_name = 2;
}

message IssueJoinTicketResponse {
  optional JoinTicket ticket = 1;
  optional Error error = 2;
}
