use anyhow::Result;
use chrono::Utc;
use serde::Deserialize;
use uuid::Uuid;

#[derive(Debug, Deserialize)]
pub(crate) struct GeneratedQuizPayload {
    pub(crate) title: String,
    pub(crate) description: Option<String>,
    pub(crate) questions: Vec<GeneratedQuestionPayload>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct GeneratedQuestionPayload {
    pub(crate) text: String,
    pub(crate) options: Vec<String>,
    pub(crate) correct_option_index: u32,
}

pub(crate) fn validate_questions(
    questions: &[proto::richcrab::v1::QuizQuestion],
) -> Result<(), String> {
    if questions.is_empty() {
        return Err("quiz must contain at least one question".to_string());
    }

    for (idx, q) in questions.iter().enumerate() {
        if q.text.trim().is_empty() {
            return Err(format!("question[{idx}] text must not be empty"));
        }
        if q.options.len() < 2 {
            return Err(format!("question[{idx}] must contain at least two options"));
        }
        for (opt_idx, option) in q.options.iter().enumerate() {
            if option.trim().is_empty() {
                return Err(format!(
                    "question[{idx}] option[{opt_idx}] must not be empty"
                ));
            }
        }
        if let Some(correct_idx) = q.correct_option_index {
            if (correct_idx as usize) >= q.options.len() {
                return Err(format!("question[{idx}] has invalid correct_option_index"));
            }
        }
    }

    Ok(())
}

pub(crate) fn strip_markdown_code_fence(raw: &str) -> &str {
    let trimmed = raw.trim();
    if let Some(rest) = trimmed.strip_prefix("```") {
        let without_lang = rest
            .find('\n')
            .and_then(|idx| rest.get(idx + 1..))
            .unwrap_or(rest);
        return without_lang.trim_end_matches("```").trim();
    }
    trimmed
}

pub(crate) fn build_quiz_from_generated_payload(
    owner_user_id: Uuid,
    parsed: GeneratedQuizPayload,
) -> Result<proto::richcrab::v1::Quiz> {
    let questions = parsed
        .questions
        .into_iter()
        .enumerate()
        .map(|(idx, q)| proto::richcrab::v1::QuizQuestion {
            id: format!("ai-{}", idx + 1),
            text: q.text,
            options: q.options,
            correct_option_index: Some(q.correct_option_index),
        })
        .collect::<Vec<_>>();

    validate_questions(&questions).map_err(anyhow::Error::msg)?;

    let now = Utc::now();
    Ok(proto::richcrab::v1::Quiz {
        quiz_id: Some(proto::richcrab::v1::QuizId {
            value: Uuid::new_v4().to_string(),
        }),
        owner_user_id: Some(proto::richcrab::v1::UserId {
            value: owner_user_id.to_string(),
        }),
        title: parsed.title,
        description: parsed
            .description
            .unwrap_or_else(|| "Generated by AI".to_string()),
        questions,
        created_at: Some(prost_types::Timestamp {
            seconds: now.timestamp(),
            nanos: now.timestamp_subsec_nanos() as i32,
        }),
        updated_at: Some(prost_types::Timestamp {
            seconds: now.timestamp(),
            nanos: now.timestamp_subsec_nanos() as i32,
        }),
    })
}

pub(crate) fn parse_generated_quiz_content(
    owner_user_id: Uuid,
    raw_content: &str,
) -> Result<proto::richcrab::v1::Quiz> {
    let parsed: GeneratedQuizPayload =
        serde_json::from_str(strip_markdown_code_fence(raw_content))?;
    build_quiz_from_generated_payload(owner_user_id, parsed)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn q(text: &str, options: &[&str], correct: Option<u32>) -> proto::richcrab::v1::QuizQuestion {
        proto::richcrab::v1::QuizQuestion {
            id: "q1".to_string(),
            text: text.to_string(),
            options: options.iter().map(|s| s.to_string()).collect(),
            correct_option_index: correct,
        }
    }

    #[test]
    fn validate_questions_rejects_empty_list() {
        assert!(validate_questions(&[]).is_err());
    }

    #[test]
    fn validate_questions_rejects_invalid_correct_index() {
        assert!(validate_questions(&[q("Q", &["a", "b"], Some(2))]).is_err());
    }

    #[test]
    fn validate_questions_accepts_valid_payload() {
        assert!(validate_questions(&[q("Q", &["a", "b"], Some(1))]).is_ok());
    }

    #[test]
    fn strip_markdown_code_fence_extracts_json() {
        let raw = "```json\n{\"title\":\"T\"}\n```";
        assert_eq!(strip_markdown_code_fence(raw), "{\"title\":\"T\"}");
    }

    #[test]
    fn strip_markdown_code_fence_plain_json_untouched() {
        let raw = "{\"title\":\"T\"}";
        assert_eq!(strip_markdown_code_fence(raw), raw);
    }

    #[test]
    fn parse_generated_quiz_content_parses_and_validates_payload() {
        let owner = Uuid::new_v4();
        let raw = r#"{
            "title":"Rust Quiz",
            "description":"desc",
            "questions":[{
                "text":"Q1",
                "options":["A","B","C","D"],
                "correct_option_index":2
            }]
        }"#;

        let quiz = parse_generated_quiz_content(owner, raw).expect("generated quiz must parse");
        assert_eq!(quiz.title, "Rust Quiz");
        assert_eq!(quiz.questions[0].correct_option_index, Some(2));
    }

    #[test]
    fn parse_generated_quiz_content_fails_on_invalid_json() {
        let owner = Uuid::new_v4();
        assert!(parse_generated_quiz_content(owner, "```json\nnot-json\n```").is_err());
    }
}
