# syntax=docker/dockerfile:1.7-labs

FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  git curl zip unzip tar ca-certificates \
  build-essential pkg-config cmake ninja-build ccache \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN git clone --depth 1 https://github.com/microsoft/vcpkg.git \
  && /opt/vcpkg/bootstrap-vcpkg.sh -disableMetrics

ENV VCPKG_ROOT=/opt/vcpkg
ENV VCPKG_FEATURE_FLAGS=manifests
ENV VCPKG_BINARY_SOURCES="clear;files,/opt/vcpkg-bincache,readwrite"
ENV VCPKG_DEFAULT_TRIPLET=x64-linux-release
ENV VCPKG_DEFAULT_HOST_TRIPLET=x64-linux-release

WORKDIR /repo/defay1x9
COPY defay1x9/vcpkg.json /repo/defay1x9/vcpkg.json
COPY defay1x9/triplets/x64-linux-release.cmake /repo/defay1x9/triplets/x64-linux-release.cmake

# Сборка и упаковка зависимостей в бинарный cache (делается редко: при изменении vcpkg.json/triplet)
RUN --mount=type=cache,target=/opt/vcpkg/downloads,id=vcpkg-downloads \
    --mount=type=cache,target=/opt/vcpkg/buildtrees,id=vcpkg-buildtrees-x64-linux-release \
    --mount=type=cache,target=/opt/vcpkg/packages,id=vcpkg-packages-x64-linux-release \
    /opt/vcpkg/vcpkg install \
      --triplet=x64-linux-release \
      --host-triplet=x64-linux-release \
      --overlay-triplets=/repo/defay1x9/triplets \
      --x-manifest-root=/repo/defay1x9 \
      --clean-after-build
