[package]
name = "shared"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
deadpool-redis = "0.18"
sha2.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["time"] }
uuid.workspace = true
prometheus = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = "0.7"
tonic = { version = "0.12" }
